### ISSUE TITLE
Port to Qt5 for re-uptake by Debian

### ISSUE THREAD

**Issue by eyalroz** [lucasw/v4l2ucp#8]
Debian has been in the process of phasing out Qt4, and in its recent stable release has dropped all Qt4-dependent packages  after notifying maintainers:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=875221

I was hoping that you would consider porting this to Qt5, so it can again be used on Debian-based distributions. Would that be possible?

PS - The Debian maintainer for the package is Alessio Treglia <alessio@debian.org>.

**Comment by lucasw** [comment]
I need to update the documentation here and maybe change the name but in this fork I've removed all qt, it uses ROS interfaces to interact with.  The upstream version https://github.com/palosaari/v4l2ucp probably is the repo to go to with this issue, I think that is an import of the old sourceforge version.

**Comment by eyalroz** [comment]
@lucasw : Sorry for being ignorant, but - what is a "ROS interface"?

I tried this repository since it had the most recent set of commits...

**Comment by lucasw** [comment]
It's the Robot Operating System https://www.ros.org/ which makes it convenient to move sensor data around, here it's v4l camera images.  It's a substantial dependency so no one would want to install it just to do v4lucp control.

**Comment by eyalroz** [comment]
@lucasw , So about this repo vs the upstream - I do notice you've made a bunch of commits resolving build issues, so the upstream might not be the one to port... how difficult would it be to move from ROS to Qt5?

**Comment by lucasw** [comment]
What about https://github.com/smunaut/v4l2ucp-qt5 ?

**Comment by eyalroz** [comment]
I'll look into it. Or rather, I'll ask Mr. Treglia to look into it.
